### ISSUE TITLE
js脚本中的包名不正确，且无法正确运行

### ISSUE THREAD

**Issue by bigoovip** [pzx521521/qidian_AutoLookAD#3]
下载最新的main_v1.0.1.apk，操作系统及起点读书app版本为Android13_7.9.308_1052，无法正确运行，问题有二：
1、main.js中的包名不对，apk安装好后的包名为com.script.sfjpuo,js脚本中的包名为com.script.main
2、脚本运行结束，但没有找到视频，实际表现是脚本启动了起点读书app，但没有点击我——福利中心

两次操作的日志如下：
![Screenshot_20231020-004317](https://github.com/pzx521521/qidian_AutoLookAD/assets/86590318/61d37406-54a7-4273-9d3b-77b763e21bb7)

**Comment by pzx521521** [comment]
包名和"我"的点击已修改, "我"增加了一层布局,现在通过判断是否可以点击  向上找"我" 详细见代码
